trigger:
- main  # Triggers the pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Using the ubuntu-latest hosted agent

variables:
  ACR_NAME: 'project3acr'  # Your ACR name without .azurecr.io
  IMAGE_TAG: 'latest'  # Tag for your Docker images

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ServiceConnection'  # Azure service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Logging in to Azure Container Registry"
      az acr login --name $(ACR_NAME)

- task: Docker@2
  inputs:
    containerRegistry: 'ServiceConnectionD'  # Docker service connection name
    repository: 'financial-app/account-service'
    command: 'buildAndPush'
    Dockerfile: 'account-service/Dockerfile'
    tags: $(IMAGE_TAG)

- task: Docker@2
  inputs:
    containerRegistry: 'ServiceConnectionD'
    repository: 'financial-app/notification-service'
    command: 'buildAndPush'
    Dockerfile: 'notification-service/Dockerfile'
    tags: $(IMAGE_TAG)

- task: Docker@2
  inputs:
    containerRegistry: 'ServiceConnectionD'
    repository: 'financial-app/transaction-service'
    command: 'buildAndPush'
    Dockerfile: 'transaction-service/Dockerfile'
    tags: $(IMAGE_TAG)

- task: Docker@2
  inputs:
    containerRegistry: 'ServiceConnectionD'
    repository: 'financial-app/user-service'
    command: 'buildAndPush'
    Dockerfile: 'user-service/Dockerfile'
    tags: $(IMAGE_TAG)
