trigger:
- main

pool:
  vmImage: 'self-hosted'

variables:
  ACR_NAME: 'project3acr'  # Replace with your ACR name without .azurecr.io
  IMAGE_TAG: 'latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ServiceConnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Logging in to Azure Container Registry"
      az acr login --name ServiceConnection

- task: Docker@2
  inputs:
    containerRegistry: 'ServiceConnectionD'
    repository: 'financial-app/account-service'  # Change as needed for each service
    command: 'buildAndPush'
    Dockerfile: 'financial-app/account-service/Dockerfile'
    tags: $(IMAGE_TAG)

- task: Docker@2
  inputs:
    containerRegistry: 'ServiceConnectionD'
    repository: 'financial-app/notification-service'
    command: 'buildAndPush'
    Dockerfile: 'financial-app/notification-service/Dockerfile'
    tags: $(IMAGE_TAG)

- task: Docker@2
  inputs:
    containerRegistry: 'ServiceConnectionD'
    repository: 'financial-app/transaction-service'
    command: 'buildAndPush'
    Dockerfile: 'financial-app/transaction-service/Dockerfile'
    tags: $(IMAGE_TAG)

- task: Docker@2
  inputs:
    containerRegistry: 'ServiceConnectionD'
    repository: 'financial-app/user-service'
    command: 'buildAndPush'
    Dockerfile: 'financial-app/user-service/Dockerfile'
    tags: $(IMAGE_TAG)
